config/routes.rb
Rails.application.routes.draw do

  root "users#index"
  resources :users
  resources :urls

  get "/login" => "users#login"
  post "/signin" => "users#signin"
  get "/logout" => "users#signout"

end

app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :user
  # Remember to create a migration!
  before_save :shorten_url
  def shorten_url
    # attribute of url, we change this attribute, but assign to the same ID
    if self.short_url.nil?
      self[:short_url] = rand(1..999).to_s + ("a".."z").to_a.sample
    end
  end

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  has_many :urls

  def display_password
    self.password
  end

  def pass
    @pass ||= Password.new(password)
  end

  def pass=(new_password)
    @pass= Password.create(new_password)
    self.password = @pass
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # respond_to :html, :js

  def index
    @urls = Url.all
  end

  def show
    @url = Url.find params[:id]
  end

  def new
    @url = Url.new

  end

  def create
    @url = Url.create(long_url: params[:url][:long_url])
    @user = User.find(session[:user])
    @user.urls << @url

      respond_to do |format|
        if @url.save
          format.html
          format.js
          # format.json { render json: @url, status: :created, location: '/users/show.html.erb' }
        end
      end
      # render json: @url
      #redirect_to url_path(@url)


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # enable :sessions
  def index

    @users = User.all
  end

  def show
    @user = User.find params[:id]
    @url = Url.new
  end

  def new
    @user = User.new
  end

  def create
    p params
    @user = User.new(:username => params[:user][:username])
    @user.pass = params[:user][:pass]
    if @user.save
      session[:user] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def login

  end

  def signin
    @user = User.find_by(:username =>params[:username])
    if @user != nil
      session[:user] = @user.id
      redirect_to user_path(@user)
    else
      render :login
    end
  end

  def edit
    @user=User.find(params[:id])
    if session[:user] == @user.id
      @user=User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  def update

    @user=User.find params[:id]
    if @user.update_attribute :password, params[:user][:password]
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user=User.find params[:id]
    user.destroy
    session[:user] = nil
    redirect_to root_path
  end

  def signout
    session[:user] = nil
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsUrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_create.html.erb
<p>Here is the url</p>

<% @user.urls.each do |url| %>
  <ul>
    <li>
      <div>Here is your long url: <%= link_to url.long_url,  url.long_url %></div>
    </li>
    <li>
      <div>Here is your short url: <%= link_to url.short_url, url.long_url %></div>
    </li>
    <br>
  </ul>
<%end %>

app/views/urls/create.js.erb
$("#url-list").html("<%= j render 'create' %>")

app/views/urls/new.html.erb
<h3>Shorten your URL!!!!</h3>
<ul>
<%= form_for @url, remote: true do |f| %>
  <li>
    <%= f.label :long_url %>
    <%= f.text_field :long_url %>
  </li>
  <li>
    <%= f.submit %>
  </li>

<% end%>
</ul>

app/views/urls/show.html.erb
<div>Here is your short url: <%= link_to @url.short_url, @url.long_url %></div>
<br>
<%= link_to "your home page", user_path(User.find(@url.user_id)) %>

app/views/users/edit.html.erb
<h1>Edit your password</h1>
<ul>
<%= form_for @user do |f| %>
  <li>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </li>
  <li>
    <%= f.submit %>
  </li>

<% end%>
</ul>

app/views/users/index.html.erb
<div id="landingPage">
  <h1> URL shortener </h1>
  <br>

  <h2>Here are the current users:</h2>
  <ul>
  <%@users.each do |user|%>
  <li><%= link_to user.username, user %></li>
  <%end%>
  </ul>



  <% if session[:user] != nil %>

  <% user = User.find(session[:user]) %>
  <div><%= user.username %> is logged in</div>
  <span><%= link_to "sign out", logout_path %></span>
  <% else %>
  <span><%= link_to "Sign Up", new_user_path %></span>
  <br>
  <span><%= link_to "login", login_path %></span>

  <% end%>

  <div class="galleria">
    <img src="<%= asset_path 'lake.jpg' %>">
  </div>
</div>

app/views/users/login.html.erb
<h1>Please login</h1>
<ul>
<%= form_tag :action => :signin do %>
  <li>
    <%= label_tag :username, "Username: " %>
    <%= text_field_tag :username %>
  </li>
  <li>
    <%= label_tag :password, "Password: " %>
    <%= text_field_tag :password %>
  </li>
  <li>
    <%= submit_tag ("Login") %>

  </li>

<% end%>
</ul>

app/views/users/new.html.erb
<h1>Create A New User</h1>
<ul>
<%= form_for @user do |f| %>
  <li>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </li>
  <li>
    <%= f.submit %>
  </li>

<% end%>
</ul>

app/views/users/show.html.erb
<div id="profilePage">
  <h1 class= "test">Hello <%= @user.username %></h1>

  <div class="test2" style="display: none"><%= @user.display_password %></div>
  <h6>Shhh... it's a secret to everybody...</h6>

  <span><%= link_to "Home Page", root_path %></span>


  <% if session[:user] == @user.id %>
  <span><%= link_to "Shorten your URL", new_url_path, remote: true  %></span>
  <span><%= link_to "edit your page", edit_user_path(@user) %></span>
  <span><%= link_to 'delete', user_path(@user), :method => :delete %></span>
  <span><%= link_to "sign out", logout_path %></span>

  <%= render template: "urls/new", :class => 'new-url' %>

  <% end%>

<div id="url-list"> </div>

<!--   <div class="url-list">
  <% @user.urls.each do |url| %>
  <ul>
    <li>
      <div>Here is your long url: <%= link_to url.long_url,  url.long_url %></div>
    </li>
    <li>
      <div>Here is your short url: <%= link_to url.short_url, url.long_url %></div>
    </li>
    <br>
  </ul>
  </div>

  <% end %>
</div>
 -->